### ISSUE TITLE
Request for the complete code

### ISSUE THREAD

**Issue by cjplol** [mousecpn/FERNet-Pytorch#1]
Hi，I have recently ran your code but use my own version of MMDetection,which can only train but will report errors when testing.I revised the code for a long time, but it didn't work out.It might be the version mismatch of mmdetection,so I wish you could release the complete of the Project which contains mmdetection and   the required files，thank you!

**Comment by mousecpn** [comment]
can you offer the printed error? It can help me give you the solution

**Comment by cjplol** [comment]
> can you offer the printed error? It can help me give you the solution

Now the error message I'm getting is the following：

File "/home/cjp/roimix/mmdet/models/dense_heads/prs_head.py", line 531, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/home/cjp/anaconda3/envs/roimix/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'PRSHead' object has no attribute '_get_bboxes_single'

It seems that the _get_bboxes_single method is missing from the prs_heads.py file

**Comment by ZYCi** [comment]
I also encountered a problem when running the code, the error message is as follows, can you help me find the reason?
2022-04-14 18:46:03,087 - mmdet - INFO - Set random seed to 725963868, deterministic: False
/home/czy/mmdetection/mmdet/models/builder.py:53: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 193, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/czy/mmdetection/mmdet/models/builder.py", line 55, in build_detector
    'train_cfg specified in both outer field and model field '
AssertionError: train_cfg specified in both outer field and model field

**Comment by mousecpn** [comment]
Got that. I am implementing a new version FERNet for the latest version of FERNet, and will upload the new ver. in a few days.

**Comment by cjplol** [comment]
> train_cfg and test_cfg is deprecated, please specify them in model

I didn't meet the problem,but I think you may check the file of "configs/FERNet300_coco.py",is the dict of "train_cfg" missing?

**Comment by cjplol** [comment]
> Got that. I am implementing a new version FERNet for the latest version of FERNet, and will upload the new ver. in a few days.

Thank you, looking forward to your update.

**Comment by mousecpn** [comment]
I have updated the code, and it can fit the current version of mmdet.

> > Got that. I am implementing a new version FERNet for the latest version of FERNet, and will upload the new ver. in a few days.
> 
> Thank you, looking forward to your update.

**Comment by cjplol** [comment]
> I have updated the code, and it can fit the current version of mmdet.
> 
> > > Got that. I am implementing a new version FERNet for the latest version of FERNet, and will upload the new ver. in a few days.
> > 
> > 
> > Thank you, looking forward to your update.

Thank you. I was too busy to try your new code a few days ago. I will try it soon.
